### ISSUE TITLE
Suggestion: Forwarding "cancel" from a DeferredFuture to underlying QtConcurrent future...

### ISSUE THREAD

**Issue by daniel-adb-fa** [benlau/asyncfuture#4] opened 2017-12-07 09:21 UTC
It's again about this type of usage pattern:

```
QFuture<double> compute(QVector<QPointF> coords) const
{
	QFuture<System> sys = getSystem();
	auto f = [=](System&& system)
	{
		return QtConcurrent::mapped(coords, Worker(system));
	};

	auto rv = AsyncFuture::observe(sys).subscribe(f);
	return rv.future();
}
``` 

In this case, if client code cancels the future returned by `compute()`, I need it to actually cancel the `QtConcurrent::mapped` operation. I may be wrong but I think that this behaviour is generally desirable, as there is nothing else I can see to which the `cancel()` could relate in this type of situation. The idea is that the `QFuture` returned by a `Observable::future()` basically "becomes" the `QFuture` returned from the lambda function. However, right now cancelling the returned `QFuture` has no effect at all.

To achieve it, I wrote the following:

```
template<typename RetType, typename InpType, typename Func>
class FutureFunctor
{
public:
	explicit FutureFunctor(Func wrapped) :
		_wrapped(wrapped),
		_s(std::make_shared<State>())
	{}

	FutureFunctor(const FutureFunctor&) = default;
	FutureFunctor(FutureFunctor&&) = default;

	void cancel() const
	{
		_s->isCancelled = true;
		_s->future.cancel();
	}

	QFuture<RetType> operator()(InpType&& input) const
	{
		Q_ASSERT(!_s->isCalled);
		_s->isCalled = true;
		if(!_s->isCancelled) {
			_s->future = _wrapped(std::forward<InpType>(input));
		}

		return _s->future;
	}

private:
	struct State {
		QFuture<RetType> future;
		bool isCalled = false;
		bool isCancelled = false;
	};

	const Func _wrapped;
	std::shared_ptr<State> _s;
};

template<typename RetType, typename InpType, typename Func>
QFuture<RetType> apply(Func f, QFuture<InpType> input)
{
	auto ff = FutureFunctor<RetType, InpType, Func>(f);
	auto rv = AsyncFuture::observe(input).subscribe(ff);
	rv.subscribe([]() {}, [ff]() { ff.cancel(); });
	return rv.future();
}
```

Applying it to the use case above, it looks like so:

```
QFuture<double> compute(QVector<QPointF> coords) const
{
    QFuture<System> sys = getSystem();
    auto f = [=](System&& system)
    {
        return QtConcurrent::mapped(coords, Worker(system));
    };

    return apply<double>(f, sys);
}
``` 

As I think that this feature can be generally useful, I thought you might want to include it in the lib, either as an additional layer like in my code, or maybe also by modifying the behaviour of `subscribe in some way.

**Comment by benlau** [comment] 2017-12-19 18:28
Hi @daniel-adb-fa ,

Thanks for pointing out this use-case. I agree that a mechanism to handle this kind of use-case is needed. However, the name of `apply` function is quite confusing. Moreover, the implementation of `FutureFunctor` is a bit complex. I think it could be replaced by the use of cancellation token suggested by #2. 

I have written an example code to demonstrate it. (not really perfect , still need to improve)

https://github.com/benlau/asyncfuture/blob/master/tests/asyncfutureunittests/example.cpp#L392
(`void Example::example_qtconcurrent_mapped_cancel()`)

**Comment by daniel-adb-fa** [comment] 2018-01-02 09:27
Hey ben, thank you for taking on the suggestion and integrating this as a feature! I haven't yet come to test it, as my version is working for me and right now I'm busy in other parts of our code. As soon as I come back to work on this part of our code, I'll update, refactor and give you feedback about it.

**Comment by daniel-adb-fa** [comment] 2018-02-06 11:35
Okay, I just updated to the latest version from the repo, and here's some more feedback concerning this use case...

First, one of the new static_asserts raises alarm when used with my `apply` function as described above...

```
static_assert( std::is_same<T, Private::Arg0Type<Completed>>::value || \
                   Private::arg0_is_future<Completed>::value || \
                   std::is_same<void, Private::Arg0Type<Completed>>::value, Tag ASYNCFUTURE_ERROR_ARGUMENT_MISMATCHED);
```

Even if there are simpler ways to achieve what is done my code, I think that putting a templated functor as callback argument is a valid use case - so this is probably a false alarm in the subscribe function?
Simply removing this assert works for me.

Then, I also applied the cancelToken mechanism as demonstrated in your test. With this, the `apply` function looks as follows:

```
template<typename RetType, typename InpType, typename Func>
inline QFuture<RetType> apply(Func f, QFuture<InpType> input)
{
	auto cancelToken = AsyncFuture::deferred<void>();
	auto rv = AsyncFuture::observe(input).subscribe([=](InpType&& in) {
		auto future = f(std::forward<InpType>(in));
		auto ct = cancelToken;
		ct.subscribe([](){}, [=]() {
			auto f = future;
			f.cancel();
		});
		return future;
	}).future();

	AsyncFuture::observe(rv).subscribe([](){}, [=]() {
		auto d = cancelToken;
		d.cancel();
	});

	return rv;
}

```

Still, the above mentioned static_assert complains about it unless I remove it.

**Comment by benlau** [comment] 2018-02-06 17:31
Which line trigger the static_asserts?

**Comment by daniel-adb-fa** [comment] 2018-02-06 17:45
It's the `subscribe` in the long line where `rv` is defined that triggers the assert.

**Comment by benlau** [comment] 2018-02-06 17:52
Could you give me a minimal example to reproduce the issue? It is a bit difficult to make it.

**Comment by daniel-adb-fa** [comment] 2018-02-06 18:11
Okay, here it is:

myobject.cpp:
```
#include <iostream>

#include <QtConcurrent/QtConcurrent>

#include "asyncfuture.h"

#include "myobject.h"

template<typename RetType, typename InpType, typename Func>
inline QFuture<RetType> apply(Func f, QFuture<InpType> input)
{
	auto cancelToken = AsyncFuture::deferred<void>();
	auto rv = AsyncFuture::observe(input).subscribe([=](InpType&& in) {
		auto future = f(std::forward<InpType>(in));
		auto ct = cancelToken;
		ct.subscribe([](){}, [=]() {
			auto f = future;
			f.cancel();
		});
		return future;
	}).future();

	AsyncFuture::observe(rv).subscribe([](){}, [=]() {
		auto d = cancelToken;
		d.cancel();
	});

	return rv;
}


QFuture<int> getFirstResult()
{
	auto rv = AsyncFuture::deferred<int>();

	// In the actual application, this may also fail...

	rv.complete(1234);
	return rv.future();
}

QFuture<double> getSecondResult()
{
	auto res = getFirstResult();
	auto f = [](int input)
	{
		std::function<double(void)> fun = [input]()
		{
			return static_cast<double>(input);
		};
		return QtConcurrent::run(fun);
	};
	return apply<double>(f, res);
}

MyObject::MyObject(QObject *parent) : QObject(parent)
{
}

void MyObject::run()
{
	auto x = getSecondResult();
	while(!x.isFinished()) {
		QCoreApplication::processEvents();
	}

	std::cout << x.result() << std::endl;
}
```

myobject.h:
```
#ifndef MYOBJECT_H
#define MYOBJECT_H

#include <QObject>

class MyObject : public QObject
{
	Q_OBJECT
public:
	explicit MyObject(QObject *parent = nullptr);

	void run();
};

#endif // MYOBJECT_H
```

main.cpp:
```
#include <QObject>
#include <QCoreApplication>
#include <QTimer>

#include "myobject.h"

int main(int argc, char *argv[])
{
	QCoreApplication a(argc, argv);

	MyObject obj;
	QTimer::singleShot(0, &obj, &MyObject::run);

	return a.exec();
}

```

**Comment by benlau** [comment] 2018-02-07 16:55
@daniel-adb-fa 

Thanks for reporting the bug. 

I have checked your code. In fact, the problem is nothing related to use templated functor as the callback argument. The static_asserts was failed to check rvalue reference type (the `InpType&& in`). So in your code, it just needs to change the type from `InpType&&`  to `InpType` . That will works.

Moreover, I have committed a fix to this issue. Could you check again with the latest version?

**Comment by daniel-adb-fa** [comment] 2018-02-07 17:26
Yes, my code now compiles against the new version. I leave the ticket open as a reminder in case you are still planning on including something like my `apply` function (with whatever name) in the library. If not, feel free to close it.

**Comment by daniel-adb-fa** [comment] 2018-09-19 10:02
Okay, sorry to wake up this old thread, but... I just realised that the version of `apply` with the `cancelToken` is not equivalent to my version with the `FutureFunctor`. Here's one of my use cases:

```
timer = new QTimer;
timer->setSingleShot(true);
...

QFuture<System> Simulation::delayedRebuildSystem()
{
	static int nTriggered = 0;
	qDebug() << "delayedRebuild call:" << ++nTrigger;
	timer->start();
	auto delay = AsyncFuture::observe(timer, &QTimer::timeout).future();
	return apply<System>(
				[this](auto) { return buildSystem(); },
				delay);
}
```

With the `cancelToken` Version of apply, `buildSystem` will still be executed once for each call of `delayedRebuildSystem`, even if the returned future had been cancelled. With my `FutureFunctor` version, it's only executed when it's not cancelled within the timer delay, which is the desired behaviour.

**Comment by vpicaver** [comment] 2019-08-05 10:26
I like this idea. It would definitely be nice to have, since I tried doing the suggested use case and it didn't work. Any updates on this?

**Comment by vpicaver** [comment] 2020-03-18 21:33
I fixed this on my fork. DeferredFuture now by default forward cancel up the pipeline of futures. No need for tokens or apply, it simply just works.  I've also added the example use case from this bug into bugtest.cpp.

**Comment by vpicaver** [comment] 2021-03-06 16:56
@benlau or @daniel-adb-fa Do you mind closing this bug? The fix has been merged into the master.

**Closed as completed** 2021-03-08 10:48 UTC
